import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Storybook Addon Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p> Page Home</p>
      </main>
    </div>
  );
}
