import { Head } from "next/document";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Storybook Addon Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p> Page Home</p>
      </main>
    </div>
  );
}

// import React from "react";

// const Home: React.FC = () => {
//   return (
//     <>
//       <div className="container">Hello, world!</div>
//       <div className="scss">
//         <p>Home Page added</p>
//       </div>
//     </>
//   );
// };

// export default Home;
